version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /apps/profile-engine
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      workflow-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /apps/profile-engine
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
