packages:
  - apps/web
  - packages/*
  - netlify/functions

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

confirmModulesPurge: false

minimumReleaseAge: 1440

overrides:
  "nanoid@<3.3.17": 3.3.17
